theme: bulma-clean-theme

# Site Settings
fixed_navbar: top
permalink: pretty
footer_menu: footer_menu
locale: "en"
lang: en
languages: ["en", "de"]
default_lang: "en"
exclude_from_localization: ["assets", "javascript", "images", "css", "public", "sitemap.xml", "customer-images.txt", "Gemfile", "robots.txt", "CNAME"]
parallel_localization: false
direction: ltr # left to right
google_analytics: # UA-xxxxxxx
title: "Set-OutlookSignatures"
description: "Email signatures and out-of-office replies for Exchange and Outlook. Full-featured, cost-effective, unsurpassed data privacy."
url: "https://set-outlooksignatures.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. "/blog"
repository: "ExplicITConsulting/set-outlooksignatures.com" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
favicon: "/assets/images/set-outlooksignatures icon.ico"
navbar_logo: "/assets/images/set-outlooksignatures logo 500px.png"
navbar_logo_alt: "Set-OutlookSignatures"
hide_share_buttons: true
force_theme: #light
gh_sponsor: 

# SEO Related
google_site_verification:
bing_site_verification:
naver_site_verification:
yandex_site_verification:
baidu_site_verification:
logo: "/assets/images/set-outlooksignatures logo 500px.png"
social:
  name: Explicit Consulting GmbH
  links:
    - https://www.linkedin.com/company/explicit-consulting-gmbh

sass:
  style: compressed
  source_dir: _sass
  sourcemap: never

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: page
      image: "/assets/images/set-outlooksignatures benefactor circle opengraph1200x630.png"
      # "/assets/images/background, vietnam golden bridge.jpg"
      hero_height: is-small
      # hero_darken: true
      lang: "en"
      locale: "en"

include:
  - ".well-known"

kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]

collections:
  posts:
    output: true

plugins:
  - jekyll-polyglot
  - jekyll-paginate-v2
  - jekyll-feed

pagination:
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title'
  # ':title - page :num'
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true
  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'
  # Optional, the default tag to use, omit to disable
  tag: ''
  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 
  # Optional,omit or set both before and after to zero to disable. 
  # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2
  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html
  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

feed:
  path: /feed.xml